spring.application.name=sdui-service
server.port=8080

# MongoDB - use env var MONGODB_URI in production
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/zeptodb}

# Redis - use env vars in production
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL:false}
